// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "MijnApp": Models
//
// Command:
// $ goagen
// --design=github.com/mijn-app/mijn-app-backend/design
// --out=$(GOPATH)/src/github.com/mijn-app/mijn-app-backend
// --version=v1.4.1

package models

import (
	"context"
	"github.com/goadesign/goa"
	uuid "github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
	"github.com/mijn-app/mijn-app-backend/app"
	"time"
)

// Model to store a journey
type Journey struct {
	ID             uuid.UUID `sql:"type:uuid;default:uuid_generate_v4()" gorm:"primary_key"` // primary key
	CreatedAt      time.Time
	Data           string
	DeletedAt      *time.Time
	Name           string
	OrganisationID uuid.UUID        `sql:"type:uuid" gorm:"index:idx_journey_organisation_id"` // Belongs To Organisation
	Published      JourneyPublished `sql:"type:smallint"`                                      // enum JourneyPublished
	Shared         JourneyShared    `sql:"type:smallint"`                                      // enum JourneyShared
	UpdatedAt      time.Time
	Organisation   Organisation
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Journey) TableName() string {
	return "journeys"

}

// JourneyDB is the implementation of the storage interface for
// Journey.
type JourneyDB struct {
	Db *gorm.DB
}

// NewJourneyDB creates a new storage type.
func NewJourneyDB(db *gorm.DB) *JourneyDB {
	return &JourneyDB{Db: db}
}

// DB returns the underlying database.
func (m *JourneyDB) DB() interface{} {
	return m.Db
}

// JourneyStorage represents the storage interface.
type JourneyStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*Journey, error)
	Get(ctx context.Context, id uuid.UUID) (*Journey, error)
	Add(ctx context.Context, journey *Journey) error
	Update(ctx context.Context, journey *Journey) error
	Delete(ctx context.Context, id uuid.UUID) error

	ListJourney(ctx context.Context, organisationID int) []*app.Journey
	OneJourney(ctx context.Context, id uuid.UUID, organisationID int) (*app.Journey, error)

	ListJourneyList(ctx context.Context, organisationID int) []*app.JourneyList
	OneJourneyList(ctx context.Context, id uuid.UUID, organisationID int) (*app.JourneyList, error)
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *JourneyDB) TableName() string {
	return "journeys"

}

// Belongs To Relationships

// JourneyFilterByOrganisation is a gorm filter for a Belongs To relationship.
func JourneyFilterByOrganisation(organisationID uuid.UUID, originaldb *gorm.DB) func(db *gorm.DB) *gorm.DB {

	if organisationID != uuid.Nil {

		return func(db *gorm.DB) *gorm.DB {
			return db.Where("organisation_id = ?", organisationID)
		}
	}
	return func(db *gorm.DB) *gorm.DB { return db }
}

// CRUD Functions

// Get returns a single Journey as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *JourneyDB) Get(ctx context.Context, id uuid.UUID) (*Journey, error) {
	defer goa.MeasureSince([]string{"goa", "db", "journey", "get"}, time.Now())

	var native Journey
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Journey
func (m *JourneyDB) List(ctx context.Context) ([]*Journey, error) {
	defer goa.MeasureSince([]string{"goa", "db", "journey", "list"}, time.Now())

	var objs []*Journey
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *JourneyDB) Add(ctx context.Context, model *Journey) error {
	defer goa.MeasureSince([]string{"goa", "db", "journey", "add"}, time.Now())

	model.ID = uuid.Must(uuid.NewV4())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding Journey", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *JourneyDB) Update(ctx context.Context, model *Journey) error {
	defer goa.MeasureSince([]string{"goa", "db", "journey", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating Journey", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *JourneyDB) Delete(ctx context.Context, id uuid.UUID) error {
	defer goa.MeasureSince([]string{"goa", "db", "journey", "delete"}, time.Now())

	err := m.Db.Where("id = ?", id).Delete(&Journey{}).Error
	if err != nil {
		goa.LogError(ctx, "error deleting Journey", "error", err.Error())
		return err
	}

	return nil
}
