// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "MijnApp": Model Helpers
//
// Command:
// $ goagen
// --design=github.com/mijn-app/mijn-app-backend/design
// --out=$(GOPATH)/src/github.com/mijn-app/mijn-app-backend
// --version=v1.4.1

package models

import (
	"context"
	"github.com/goadesign/goa"
	uuid "github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
	"github.com/mijn-app/mijn-app-backend/app"
	"time"
)

// MediaType Retrieval Functions

// ListOrderattachment returns an array of view: default.
func (m *OrderAttachmentDB) ListOrderattachment(ctx context.Context, orderID uuid.UUID) []*app.Orderattachment {
	defer goa.MeasureSince([]string{"goa", "db", "orderattachment", "listorderattachment"}, time.Now())

	var native []*OrderAttachment
	var objs []*app.Orderattachment
	err := m.Db.Scopes(OrderAttachmentFilterByOrder(orderID, m.Db)).Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing OrderAttachment", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.OrderAttachmentToOrderattachment())
	}

	return objs
}

// OrderAttachmentToOrderattachment loads a OrderAttachment and builds the default view of media type Orderattachment.
func (m *OrderAttachment) OrderAttachmentToOrderattachment() *app.Orderattachment {
	orderattachment := &app.Orderattachment{}
	orderattachment.ID = &m.ID
	orderattachment.Path = &m.Path

	return orderattachment
}

// OneOrderattachment loads a OrderAttachment and builds the default view of media type Orderattachment.
func (m *OrderAttachmentDB) OneOrderattachment(ctx context.Context, id uuid.UUID, orderID uuid.UUID) (*app.Orderattachment, error) {
	defer goa.MeasureSince([]string{"goa", "db", "orderattachment", "oneorderattachment"}, time.Now())

	var native OrderAttachment
	err := m.Db.Scopes(OrderAttachmentFilterByOrder(orderID, m.Db)).Table(m.TableName()).Preload("Order").Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting OrderAttachment", "error", err.Error())
		return nil, err
	}

	view := *native.OrderAttachmentToOrderattachment()
	return &view, err
}
