// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "MijnApp": Models
//
// Command:
// $ goagen
// --design=github.com/mijn-app/mijn-app-backend/design
// --out=$(GOPATH)/src/github.com/mijn-app/mijn-app-backend
// --version=v1.4.1

package models

import (
	"context"
	"github.com/goadesign/goa"
	uuid "github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
	"github.com/mijn-app/mijn-app-backend/app"
	"time"
)

// Model to store file attached to an order.
type OrderAttachment struct {
	ID        uuid.UUID `sql:"type:uuid;default:uuid_generate_v4()" gorm:"primary_key"` // primary key
	CreatedAt time.Time
	DeletedAt *time.Time
	OrderID   uuid.UUID `sql:"type:uuid" gorm:"index:idx_order_attachment_order_id"` // Belongs To Order
	Path      string
	UpdatedAt time.Time
	Order     Order
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m OrderAttachment) TableName() string {
	return "order_attachments"

}

// OrderAttachmentDB is the implementation of the storage interface for
// OrderAttachment.
type OrderAttachmentDB struct {
	Db *gorm.DB
}

// NewOrderAttachmentDB creates a new storage type.
func NewOrderAttachmentDB(db *gorm.DB) *OrderAttachmentDB {
	return &OrderAttachmentDB{Db: db}
}

// DB returns the underlying database.
func (m *OrderAttachmentDB) DB() interface{} {
	return m.Db
}

// OrderAttachmentStorage represents the storage interface.
type OrderAttachmentStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*OrderAttachment, error)
	Get(ctx context.Context, id uuid.UUID) (*OrderAttachment, error)
	Add(ctx context.Context, orderattachment *OrderAttachment) error
	Update(ctx context.Context, orderattachment *OrderAttachment) error
	Delete(ctx context.Context, id uuid.UUID) error

	ListOrderattachment(ctx context.Context, orderID int) []*app.Orderattachment
	OneOrderattachment(ctx context.Context, id uuid.UUID, orderID int) (*app.Orderattachment, error)
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *OrderAttachmentDB) TableName() string {
	return "order_attachments"

}

// Belongs To Relationships

// OrderAttachmentFilterByOrder is a gorm filter for a Belongs To relationship.
func OrderAttachmentFilterByOrder(orderID uuid.UUID, originaldb *gorm.DB) func(db *gorm.DB) *gorm.DB {

	if orderID != uuid.Nil {

		return func(db *gorm.DB) *gorm.DB {
			return db.Where("order_id = ?", orderID)
		}
	}
	return func(db *gorm.DB) *gorm.DB { return db }
}

// CRUD Functions

// Get returns a single OrderAttachment as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *OrderAttachmentDB) Get(ctx context.Context, id uuid.UUID) (*OrderAttachment, error) {
	defer goa.MeasureSince([]string{"goa", "db", "orderAttachment", "get"}, time.Now())

	var native OrderAttachment
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of OrderAttachment
func (m *OrderAttachmentDB) List(ctx context.Context) ([]*OrderAttachment, error) {
	defer goa.MeasureSince([]string{"goa", "db", "orderAttachment", "list"}, time.Now())

	var objs []*OrderAttachment
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *OrderAttachmentDB) Add(ctx context.Context, model *OrderAttachment) error {
	defer goa.MeasureSince([]string{"goa", "db", "orderAttachment", "add"}, time.Now())

	model.ID = uuid.Must(uuid.NewV4())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding OrderAttachment", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *OrderAttachmentDB) Update(ctx context.Context, model *OrderAttachment) error {
	defer goa.MeasureSince([]string{"goa", "db", "orderAttachment", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating OrderAttachment", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *OrderAttachmentDB) Delete(ctx context.Context, id uuid.UUID) error {
	defer goa.MeasureSince([]string{"goa", "db", "orderAttachment", "delete"}, time.Now())

	err := m.Db.Where("id = ?", id).Delete(&OrderAttachment{}).Error
	if err != nil {
		goa.LogError(ctx, "error deleting OrderAttachment", "error", err.Error())
		return err
	}

	return nil
}
