// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "MijnApp": Models
//
// Command:
// $ goagen
// --design=github.com/mijn-app/mijn-app-backend/design
// --out=$(GOPATH)/src/github.com/mijn-app/mijn-app-backend
// --version=v1.4.1

package models

import (
	"context"
	"github.com/goadesign/goa"
	uuid "github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
	"github.com/mijn-app/mijn-app-backend/app"
	"time"
)

// Model to store data from a user in an organisation.
type UserOrganisationData struct {
	ID             uuid.UUID `sql:"type:uuid;default:uuid_generate_v4()" gorm:"primary_key"` // primary key
	CreatedAt      time.Time
	DeletedAt      *time.Time
	ForeignID      string
	ForeignToken   string
	OrganisationID uuid.UUID `sql:"type:uuid" gorm:"index:idx_user_organisation_data_organisation_id"` // Belongs To Organisation
	UpdatedAt      time.Time
	UserID         uuid.UUID `sql:"type:uuid" gorm:"index:idx_user_organisation_data_user_id"` // Belongs To User
	Organisation   Organisation
	User           User
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m UserOrganisationData) TableName() string {
	return "user_organisation_data"

}

// UserOrganisationDataDB is the implementation of the storage interface for
// UserOrganisationData.
type UserOrganisationDataDB struct {
	Db *gorm.DB
}

// NewUserOrganisationDataDB creates a new storage type.
func NewUserOrganisationDataDB(db *gorm.DB) *UserOrganisationDataDB {
	return &UserOrganisationDataDB{Db: db}
}

// DB returns the underlying database.
func (m *UserOrganisationDataDB) DB() interface{} {
	return m.Db
}

// UserOrganisationDataStorage represents the storage interface.
type UserOrganisationDataStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*UserOrganisationData, error)
	Get(ctx context.Context, id uuid.UUID) (*UserOrganisationData, error)
	Add(ctx context.Context, userorganisationdata *UserOrganisationData) error
	Update(ctx context.Context, userorganisationdata *UserOrganisationData) error
	Delete(ctx context.Context, id uuid.UUID) error

	ListUserorganisationdatamedia(ctx context.Context, organisationID int, userID int) []*app.Userorganisationdatamedia
	OneUserorganisationdatamedia(ctx context.Context, id uuid.UUID, organisationID int, userID int) (*app.Userorganisationdatamedia, error)
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *UserOrganisationDataDB) TableName() string {
	return "user_organisation_data"

}

// Belongs To Relationships

// UserOrganisationDataFilterByOrganisation is a gorm filter for a Belongs To relationship.
func UserOrganisationDataFilterByOrganisation(organisationID uuid.UUID, originaldb *gorm.DB) func(db *gorm.DB) *gorm.DB {

	if organisationID != uuid.Nil {

		return func(db *gorm.DB) *gorm.DB {
			return db.Where("organisation_id = ?", organisationID)
		}
	}
	return func(db *gorm.DB) *gorm.DB { return db }
}

// Belongs To Relationships

// UserOrganisationDataFilterByUser is a gorm filter for a Belongs To relationship.
func UserOrganisationDataFilterByUser(userID uuid.UUID, originaldb *gorm.DB) func(db *gorm.DB) *gorm.DB {

	if userID != uuid.Nil {

		return func(db *gorm.DB) *gorm.DB {
			return db.Where("user_id = ?", userID)
		}
	}
	return func(db *gorm.DB) *gorm.DB { return db }
}

// CRUD Functions

// Get returns a single UserOrganisationData as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *UserOrganisationDataDB) Get(ctx context.Context, id uuid.UUID) (*UserOrganisationData, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userOrganisationData", "get"}, time.Now())

	var native UserOrganisationData
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of UserOrganisationData
func (m *UserOrganisationDataDB) List(ctx context.Context) ([]*UserOrganisationData, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userOrganisationData", "list"}, time.Now())

	var objs []*UserOrganisationData
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *UserOrganisationDataDB) Add(ctx context.Context, model *UserOrganisationData) error {
	defer goa.MeasureSince([]string{"goa", "db", "userOrganisationData", "add"}, time.Now())

	model.ID = uuid.Must(uuid.NewV4())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding UserOrganisationData", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *UserOrganisationDataDB) Update(ctx context.Context, model *UserOrganisationData) error {
	defer goa.MeasureSince([]string{"goa", "db", "userOrganisationData", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating UserOrganisationData", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *UserOrganisationDataDB) Delete(ctx context.Context, id uuid.UUID) error {
	defer goa.MeasureSince([]string{"goa", "db", "userOrganisationData", "delete"}, time.Now())

	err := m.Db.Where("id = ?", id).Delete(&UserOrganisationData{}).Error
	if err != nil {
		goa.LogError(ctx, "error deleting UserOrganisationData", "error", err.Error())
		return err
	}

	return nil
}
