// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "MijnApp": Model Helpers
//
// Command:
// $ goagen
// --design=github.com/mijn-app/mijn-app-backend/design
// --out=$(GOPATH)/src/github.com/mijn-app/mijn-app-backend
// --version=v1.4.1

package models

import (
	"context"
	"github.com/goadesign/goa"
	uuid "github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
	"github.com/mijn-app/mijn-app-backend/app"
	"time"
)

// MediaType Retrieval Functions

// ListUserorganisationdatamedia returns an array of view: default.
func (m *UserOrganisationDataDB) ListUserorganisationdatamedia(ctx context.Context, organisationID uuid.UUID, userID uuid.UUID) []*app.Userorganisationdatamedia {
	defer goa.MeasureSince([]string{"goa", "db", "userorganisationdatamedia", "listuserorganisationdatamedia"}, time.Now())

	var native []*UserOrganisationData
	var objs []*app.Userorganisationdatamedia
	err := m.Db.Scopes(UserOrganisationDataFilterByOrganisation(organisationID, m.Db), UserOrganisationDataFilterByUser(userID, m.Db)).Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing UserOrganisationData", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.UserOrganisationDataToUserorganisationdatamedia())
	}

	return objs
}

// UserOrganisationDataToUserorganisationdatamedia loads a UserOrganisationData and builds the default view of media type Userorganisationdatamedia.
func (m *UserOrganisationData) UserOrganisationDataToUserorganisationdatamedia() *app.Userorganisationdatamedia {
	userorganisationdata := &app.Userorganisationdatamedia{}
	userorganisationdata.ForeignID = &m.ForeignID
	userorganisationdata.ForeignToken = &m.ForeignToken
	userorganisationdata.ID = &m.ID

	return userorganisationdata
}

// OneUserorganisationdatamedia loads a UserOrganisationData and builds the default view of media type Userorganisationdatamedia.
func (m *UserOrganisationDataDB) OneUserorganisationdatamedia(ctx context.Context, id uuid.UUID, organisationID uuid.UUID, userID uuid.UUID) (*app.Userorganisationdatamedia, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userorganisationdatamedia", "oneuserorganisationdatamedia"}, time.Now())

	var native UserOrganisationData
	err := m.Db.Scopes(UserOrganisationDataFilterByOrganisation(organisationID, m.Db), UserOrganisationDataFilterByUser(userID, m.Db)).Table(m.TableName()).Preload("Organisation").Preload("User").Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting UserOrganisationData", "error", err.Error())
		return nil, err
	}

	view := *native.UserOrganisationDataToUserorganisationdatamedia()
	return &view, err
}
